/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[Beer]
(
[BeerID] [int] NOT NULL IDENTITY(1, 1),
[Name] [varchar] (50) NOT NULL
)
GO
ALTER TABLE [dbo].[Beer] ADD CONSTRAINT [PK_Beer] PRIMARY KEY CLUSTERED ([BeerID])
GO
