/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[Brewer]
(
[BrewerID] [int] NOT NULL IDENTITY(1, 1)
)
GO
ALTER TABLE [dbo].[Brewer] ADD CONSTRAINT [PK_Brewer] PRIMARY KEY CLUSTERED ([BrewerID])
GO
