CREATE TABLE [dbo].[Beer]
(
[BeerID] [int] NOT NULL IDENTITY(1, 1),
[Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Beer] ADD CONSTRAINT [PK_Beer] PRIMARY KEY CLUSTERED ([BeerID]) ON [PRIMARY]
GO
